# Generated by Django 5.2 on 2025-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('products', '0002_product_category_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Regular Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='master.tag'),
        ),
    ]
