# Generated by Django 5.2 on 2025-05-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('products', '0002_product_category_product_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomepageData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('popular', models.ManyToManyField(to='products.product')),
                ('trending', models.ManyToManyField(related_name='homepagedata_trending', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='HomepagePrimaryBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Homepage_banner_category', to='master.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Homepage_banner_product_primary', to='products.product')),
            ],
        ),
    ]
