# Generated by Django 5.2 on 2025-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepagePrimaryBanner',
        ),
    ]
