# Generated by Django 5.2 on 2025-04-26 05:02

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('farm_type', models.CharField(choices=[('organic', 'Organic'), ('conventional', 'Conventional'), ('mixed', 'Mixed')], max_length=20)),
                ('land_area_in_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('yield_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_productions', to='farmer.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=10, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('street_address', models.TextField()),
                ('nid_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='National ID')),
                ('nid_document', models.FileField(blank=True, null=True, upload_to='documents/nid/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='farmers/profile_pics/')),
                ('land_area_in_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('primary_crop', models.CharField(blank=True, max_length=100, null=True)),
                ('farming_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmer.farmer'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='farmers/certifications/')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='farmer.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('nid', 'National ID'), ('land_ownership', 'Land Ownership Certificate'), ('tax', 'Tax Clearance'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='farmers/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farmer.farmer')),
            ],
        ),
    ]
