# Generated by Django 5.2 on 2025-05-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created',
        ),
    ]
