# Generated by Django 5.2 on 2025-05-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created',
        ),
    ]
